"use client";
import {useRef,useState} from "react";
import {createAudioRecorder} from "@/lib/media-recorder";
export type ExtraValue={drawing?:string;audio?:string;image?:string};
export default function CaptureExtras({onChange}:{onChange:(value:ExtraValue)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),history=useRef<string[]>([]),recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);const [tool,setTool]=useState<"pen"|"eraser">("pen"),[recording,setRecording]=useState(false),[audio,setAudio]=useState(""),[image,setImage]=useState("");
 const emit=(next?:Partial<ExtraValue>)=>onChange({drawing:canvas.current?.toDataURL(),audio,image,...next});
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=canvas.current;if(!c)return;history.current.push(c.toDataURL());drawing.current=true;const p=point(e),x=c.getContext("2d")!;x.beginPath();x.moveTo(p.x,p.y);c.setPointerCapture(e.pointerId)};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current||!canvas.current)return;const p=point(e),x=canvas.current.getContext("2d")!;x.lineWidth=tool==="pen"?6:24;x.lineCap="round";x.strokeStyle=tool==="pen"?"#47725c":"#fff";x.lineTo(p.x,p.y);x.stroke()};
 const end=()=>{drawing.current=false;emit()};const restore=(url?:string)=>{const c=canvas.current;if(!c)return;const x=c.getContext("2d")!;x.clearRect(0,0,c.width,c.height);if(url){const i=new Image();i.onload=()=>{x.drawImage(i,0,0);emit()};i.src=url}else emit()};
 const record=async()=>{if(recording){recorder.current?.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),r=createAudioRecorder(stream);chunks.current=[];r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=()=>{const blob=new Blob(chunks.current,{type:r.mimeType.split(";")[0]||r.mimeType}),reader=new FileReader();reader.onload=()=>{const value=String(reader.result);setAudio(value);emit({audio:value})};reader.readAsDataURL(blob);stream.getTracks().forEach(t=>t.stop());setRecording(false)};r.start();recorder.current=r;setRecording(true);setTimeout(()=>r.state==="recording"&&r.stop(),15000)}catch{alert("마이크를 사용할 수 없어요. 소리 없이도 계속 만들 수 있어요.")}};
 return <div className="extras no-print"><h3>마음을 더 담아볼까요? (선택)</h3><label className="media-photo">📷 사진으로 남기기<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>{const value=String(r.result);setImage(value);emit({image:value})};r.readAsDataURL(f)}}}/></label>{image&&<img className="media-preview" src={image} alt="선택한 사진"/>}<div className="tools"><button className={tool==="pen"?"active":""} onClick={()=>setTool("pen")}>✏️ 펜</button><button className={tool==="eraser"?"active":""} onClick={()=>setTool("eraser")}>🧽 지우기</button><button onClick={()=>restore(history.current.pop())}>↶ 되돌리기</button><button onClick={()=>{history.current.push(canvas.current?.toDataURL()||"");restore()}}>모두 지우기</button></div><canvas ref={canvas} width={700} height={260} onPointerDown={start} onPointerMove={move} onPointerUp={end}/><button className="record" onClick={record}>{recording?"🔴 담고 있어요 · 마치기":audio?"🔄 다시 녹음":"🎙️ 목소리 담기"}</button>{audio&&<><b role="status">✅ 목소리를 담았어요</b><audio aria-label="내 목소리 들어보기" controls src={audio}/></>}</div>
}
