"use client";
import {ChangeEvent,useEffect,useMemo,useState} from "react";
import CaptureExtras,{ExtraValue} from "./CaptureExtras";
import PrintableCard,{PrintableData} from "./PrintableCard";
import {assignments,feelings,symbols} from "@/lib/demo-data";
import {DemoState,initialDemoState,localDemoRepository,ManagedStudent,studentAvatars} from "@/lib/demo-repository";

type Screen="login"|"classes"|"dashboard"|"pick"|"home"|"mood"|"done"|"friend"|"nature"|"treasure"|"relation"|"today"|"manage"|"individual"|"cycle";
const today=()=>new Intl.DateTimeFormat("ko-KR",{dateStyle:"long"}).format(new Date());
export default function DemoApp(){
 const [data,setData]=useState<DemoState>(initialDemoState),[ready,setReady]=useState(false),[screen,setScreen]=useState<Screen>("login"),[classId,setClassId]=useState("sun"),[kidId,setKidId]=useState(""),[teacherKidId,setTeacherKidId]=useState(""),[a,setA]=useState(""),[b,setB]=useState(""),[note,setNote]=useState(""),[extras,setExtras]=useState<ExtraValue>({}),[photo,setPhoto]=useState(""),[stamp,setStamp]=useState("🌱"),[friendText,setFriendText]=useState("");
 useEffect(()=>{setData(localDemoRepository.load());setReady(true)},[]);useEffect(()=>{if(ready)localDemoRepository.save(data)},[data,ready]);
 const cls=data.classes.find(c=>c.id===classId)??data.classes[0],active=cls.students.filter(s=>s.active),participants=active.filter(s=>s.attendance==="present"),kid=cls.students.find(s=>s.id===kidId),teacherKid=cls.students.find(s=>s.id===teacherKidId);
 const map=useMemo(()=>assignments(participants),[participants]),friend=kid?participants.find(s=>s.id===map.get(kid.id)):undefined,used=kid?data.natureCards.filter(c=>c.from===kid.id).map(c=>c.to):[];
 const patchData=(fn:(draft:DemoState)=>DemoState)=>setData(old=>fn(old));const updateClass=(fn:(c:typeof cls)=>typeof cls)=>patchData(old=>({...old,classes:old.classes.map(c=>c.id===classId?fn(c):c)}));
 const student=(id:string)=>data.classes.flatMap(c=>c.students).find(s=>s.id===id);const moodCard=(s:ManagedStudent):PrintableData|undefined=>{const m=data.moods[s.id];return m&&{id:`mood-${s.id}`,kind:"오늘 내 마음",name:s.name,avatar:s.avatar,date:m.date,emoji:m.a+m.b,note:m.note,drawing:m.drawing,audio:m.audio}};
 const natureCard=(card:DemoState["natureCards"][number]):PrintableData=>({id:card.id,kind:"자연 마음카드",name:student(card.from)?.name||"",avatar:student(card.from)?.avatar,date:card.date,emoji:card.emoji,image:card.image,sender:student(card.from)?.name,receiver:student(card.to)?.name});
 const friendCard=(card:DemoState["friendRecords"][number]):PrintableData=>({id:card.id,kind:"오늘의 마음친구",name:student(card.to)?.name||"",avatar:student(card.to)?.avatar,date:card.date,note:card.text,drawing:card.drawing,audio:card.audio,sender:student(card.from)?.name,receiver:student(card.to)?.name});
 const readPhoto=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setPhoto(String(r.result));r.readAsDataURL(f)}};

 if(screen==="login")return <Shell><div className="hero"><i>🌱</i><p>마음과 자연을 잇는 따뜻한 편지</p><h1>마음씨앗 우체국</h1><span>아이들의 서로 다른 표현이 모두 소중해요.</span><button onClick={()=>setScreen("classes")}>교사 Demo 로그인</button><small>실제 개인정보를 사용하지 않는 Demo Mode입니다.</small></div></Shell>;
 if(screen==="classes")return <Shell><Head title="담당 학급을 선택해 주세요" back={()=>setScreen("login")}/><div className="classes">{data.classes.map((c,i)=><button className="tile" key={c.id} onClick={()=>{setClassId(c.id);setScreen("dashboard")}}><i>{["☀️","⭐","🌿"][i]}</i><b>{c.name}</b><small>활성 유아 {c.students.filter(s=>s.active).length}명</small></button>)}</div></Shell>;
 if(screen==="dashboard")return <Shell><Head title={`${cls.name} 교사 대시보드`} back={()=>setScreen("classes")}/><aside>오늘도 아이들의 마음을 천천히 살펴보세요.</aside><div className="menu"><Menu icon="💛" name="오늘의 마음" sub={`${active.filter(s=>data.moods[s.id]).length}명 작성`} go={()=>setScreen("today")}/><Menu icon="🕸️" name="우리 반 관계지도" sub="자발적 자연 마음 연결" go={()=>setScreen("relation")}/><Menu icon="🧒" name="개별 유아 보기" sub="기록과 교사 메모" go={()=>setScreen("individual")}/><Menu icon="🌿" name="자발적 마음 사이클" sub={`${data.natureCards.filter(c=>c.from.startsWith(classId)).length}장 전송`} go={()=>setScreen("cycle")}/><Menu icon="👥" name="유아 관리" sub={`활성 ${active.length}명`} go={()=>setScreen("manage")}/><button className="tile dark" onClick={()=>{setKidId("");setScreen("pick")}}><i>📮</i><b>유아모드 시작</b><small>큰 화면으로 전환</small></button></div></Shell>;

 if(screen==="manage")return <Shell><Head title={`${cls.name} 유아 관리`} back={()=>setScreen("dashboard")}/><section className="manage-head no-print"><label>학급명<input value={cls.name} onChange={e=>updateClass(c=>({...c,name:e.target.value}))}/></label><button disabled={active.length>=25} onClick={()=>{const id=`${classId}-${Date.now()}`;updateClass(c=>({...c,students:[...c.students,{id,name:"새 원아",avatar:"🐻",active:true,attendance:"present"}]}))}}>＋ 원아 추가</button>{active.length>=25&&<p>활성 원아는 한 학급에 최대 25명까지 등록할 수 있어요. 기존 원아를 비활성으로 전환한 뒤 추가해 주세요.</p>}</section><div className="manage-list">{cls.students.map(s=><article key={s.id} className={!s.active?"inactive":""}><select aria-label={`${s.name} 아바타`} value={s.avatar} onChange={e=>updateClass(c=>({...c,students:c.students.map(x=>x.id===s.id?{...x,avatar:e.target.value}:x)}))}>{studentAvatars.map(v=><option key={v}>{v}</option>)}</select><input aria-label="원아 이름" value={s.name} onChange={e=>updateClass(c=>({...c,students:c.students.map(x=>x.id===s.id?{...x,name:e.target.value}:x)}))}/><button disabled={!s.active&&active.length>=25} onClick={()=>updateClass(c=>({...c,students:c.students.map(x=>x.id===s.id?{...x,active:!x.active}:x)}))}>{s.active?"활성 → 비활성":active.length>=25?"25명 제한":"비활성 → 활성"}</button></article>)}</div></Shell>;

 if(screen==="today")return <Shell><Head title={`${cls.name} 오늘의 마음`} back={()=>setScreen("dashboard")}/>{teacherKid?<TeacherMoodDetail student={teacherKid} card={moodCard(teacherKid)} close={()=>setTeacherKidId("")}/>:<div className="teacher-students">{active.map(s=>{const made=!!data.moods[s.id],friendDone=data.friendRecords.some(r=>r.from===s.id);return <article key={s.id}><button className="student-summary" disabled={!made} onClick={()=>setTeacherKidId(s.id)}><i>{s.avatar}</i><b>{s.name}</b><span className={made?"ok":"wait"}>{made?"마음 작성 완료":"마음 미작성"}</span><span className={friendDone?"ok":"wait"}>{friendDone?"마음친구 완료":"마음친구 미완료"}</span></button><select value={s.attendance} onChange={e=>updateClass(c=>({...c,students:c.students.map(x=>x.id===s.id?{...x,attendance:e.target.value as ManagedStudent["attendance"]}:x)}))}><option value="present">출석</option><option value="absent">결석</option><option value="excluded">활동 제외</option></select></article>})}</div>}</Shell>;

 if(screen==="individual")return <Shell><Head title={`${cls.name} 개별 유아 보기`} back={()=>{setTeacherKidId("");setScreen("dashboard")}}/><div className="teacher-picker no-print">{active.map(s=><button className={teacherKidId===s.id?"selected":""} key={s.id} onClick={()=>setTeacherKidId(s.id)}>{s.avatar} {s.name}</button>)}</div>{teacherKid?<Individual student={teacherKid} mood={moodCard(teacherKid)} friends={data.friendRecords.filter(r=>r.from===teacherKid.id||r.to===teacherKid.id).map(friendCard)} sent={data.natureCards.filter(c=>c.from===teacherKid.id).map(natureCard)} received={data.natureCards.filter(c=>c.to===teacherKid.id).map(natureCard)} total={Math.max(0,active.length-1)} note={data.notes[teacherKid.id]||""} saveNote={value=>patchData(old=>({...old,notes:{...old.notes,[teacherKid.id]:value}}))}/>:<Empty text="원아를 선택하면 기록을 한 화면에서 볼 수 있어요."/>}</Shell>;

 if(screen==="cycle")return <Shell><Head title={`${cls.name} 자발적 마음 사이클`} back={()=>setScreen("dashboard")}/><aside>각 유아는 같은 사이클에서 친구에게 한 번씩 자연 마음을 보냅니다.</aside><div className="cycle-list">{active.map(s=>{const count=data.natureCards.filter(c=>c.from===s.id).length,total=Math.max(0,active.length-1);return <article key={s.id}><i>{s.avatar}</i><b>{s.name}</b><progress max={Math.max(1,total)} value={count}/><span>{count} / {total}명에게 보냄</span><em>{total>0&&count>=total?"개인 사이클 완료":"진행 중"}</em></article>})}</div></Shell>;

 if(screen==="pick")return <Shell><Head title={`🌱 ${cls.name} 마음씨앗 우체국`} back={()=>setScreen("dashboard")}/><h2>나는 누구일까요?</h2><Kids list={active} choose={s=>{setKidId(s.id);setScreen("home")}}/></Shell>;
 if(screen==="home"&&kid)return <Shell><Head title={`${kid.avatar} ${kid.name}의 마음씨앗 우체국`} back={()=>setScreen("pick")}/><div className="home"><button onClick={()=>{setA("");setB("");setNote("");setExtras({});setScreen("mood")}}><i>💛</i><b>오늘 내 마음</b><small>{data.moods[kid.id]?`${data.moods[kid.id].a}${data.moods[kid.id].b} 담았어요`:"내 마음을 담아요"}</small></button><button onClick={()=>{setExtras({});setFriendText("");setScreen("friend")}}><i>💌</i><b>오늘의 마음친구</b><small>친구의 마음을 만나요</small></button><button onClick={()=>setScreen("nature")}><i>🌿</i><b>자연 마음 보내기</b><small>자연의 보물을 나눠요</small></button><button onClick={()=>setScreen("treasure")}><i>🎁</i><b>내 보물창고</b><small>마음 보물이 모이고 있어요</small></button></div></Shell>;
 if(screen==="mood"&&kid)return <Shell><Head title="오늘 내 마음" back={()=>setScreen("home")}/><h2>오늘 내 마음은 어떤 마음일까?</h2><Pick title="첫 번째 마음" list={feelings} value={a} set={setA}/><Pick title="두 번째 자연" list={symbols} value={b} set={setB}/>{a&&b&&<div className="badge"><i>{a}{b}</i><b>{kid.name}의 마음씨앗</b></div>}<CaptureExtras onChange={setExtras}/><label className="note">짧은 말로도 남길 수 있어요 (선택)<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={!a||!b} onClick={()=>{patchData(old=>({...old,moods:{...old.moods,[kid.id]:{a,b,note,...extras,date:today()}}}));setScreen("done")}}>내 마음 담기</button></Shell>;
 if(screen==="done"&&kid){const card=moodCard(kid);return <Shell><Head title="완성된 오늘의 마음" back={()=>setScreen("home")}/>{card&&<PrintableCard data={card} large/>}<p className="success">오늘의 마음이 담겼어요 🌱</p><button className="primary no-print" onClick={()=>setScreen("home")}>우체국으로 돌아가기</button></Shell>}
 if(screen==="friend"&&kid){if(!friend)return <Shell><Head title="오늘의 마음친구" back={()=>setScreen("home")}/><Empty text="오늘 활동에 참여하는 친구가 두 명 이상일 때 열려요."/></Shell>;const m=data.moods[friend.id]||{a:"😊",b:"🌱",note:""},done=data.friendRecords.some(r=>r.from===kid.id);return <Shell><Head title="오늘의 마음친구" back={()=>setScreen("home")}/><div className="friend"><i>{friend.avatar}</i><h2>오늘 {friend.name}의 마음을 만나볼까요?</h2><strong>{m.a}{m.b}</strong><p>{m.note||"친구가 마음씨앗을 소중히 담았어요."}</p></div><CaptureExtras onChange={setExtras}/><div className="words">{["같이 놀자","고마워","괜찮아?","같이 해도 될까?"].map(x=><button className={friendText===x?"selected":""} key={x} onClick={()=>setFriendText(x)}>{x}</button>)}</div><button className="primary" disabled={done} onClick={()=>patchData(old=>({...old,friendRecords:[...old.friendRecords,{id:`friend-${Date.now()}`,from:kid.id,to:friend.id,text:friendText,...extras,date:today()}]}))}>{done?"친구에게 보냈어요 💌":"친구에게 보내기"}</button></Shell>}
 if(screen==="nature"&&kid)return <Shell><Head title="자연 마음 보내기" back={()=>setScreen("home")}/><h2>친구에게 보여주고 싶은 자연의 보물을 찾아볼까요?</h2><label className="upload">{photo?<img src={photo} alt="선택한 자연 사진"/>:<><i>📷</i><b>자연 사진 고르기</b><small>카메라로 찍거나 사진을 골라요</small></>}<input type="file" accept="image/*" capture="environment" onChange={readPhoto}/></label>{photo&&<><Pick title="사진에 마음을 더해요" list={["🌱","🌸","☀️","🌈","🦋","💛"]} value={stamp} set={setStamp}/><h2>누구에게 보내고 싶나요?</h2><Kids list={active.filter(s=>s.id!==kid.id&&!used.includes(s.id))} choose={s=>{patchData(old=>({...old,natureCards:[...old.natureCards,{id:`nature-${Date.now()}`,from:kid.id,to:s.id,image:photo,emoji:stamp,date:today()}]}));setPhoto("");setScreen("home")}}/></>}</Shell>;
 if(screen==="treasure"&&kid){const received=data.natureCards.filter(c=>c.to===kid.id);return <Shell><Head title="내 보물창고" back={()=>setScreen("home")}/><h2>친구들의 마음 보물이 차곡차곡 모이고 있어요 🎁</h2>{received.length?<div className="card-gallery">{received.map(c=><PrintableCard key={c.id} data={natureCard(c)}/>)}</div>:<Empty text="마음 보물이 도착하면 이곳에서 만날 수 있어요."/>}</Shell>}
 return <Shell><Head title={`${cls.name} 우리 반 관계지도`} back={()=>setScreen("dashboard")}/><aside>이 기록은 활동 안의 자발적 선택을 시각화한 관찰 보조자료이며, 유아의 사회성이나 또래관계를 진단하지 않습니다.</aside><div className="relations">{data.natureCards.filter(c=>c.from.startsWith(classId)).length===0?<p>아직 연결이 없습니다. 유아모드에서 자연 마음을 보내 보세요.</p>:data.natureCards.filter(c=>c.from.startsWith(classId)).map(c=>{const f=student(c.from)!,t=student(c.to)!;return <div key={c.id}><i>{f.avatar}</i><b>{f.name}</b><strong>→</strong><i>{t.avatar}</i><b>{t.name}</b><em>{c.emoji}</em></div>})}</div></Shell>
}

function Shell({children}:{children:React.ReactNode}){return <main>{children}</main>}
function Head({title,back}:{title:string;back:()=>void}){return <header className="no-print"><button onClick={back}>← 뒤로</button><b>{title}</b></header>}
function Menu({icon,name,sub,go}:{icon:string;name:string;sub:string;go:()=>void}){return <button className="tile" onClick={go}><i>{icon}</i><b>{name}</b><small>{sub}</small></button>}
function Kids({list,choose}:{list:ManagedStudent[];choose:(s:ManagedStudent)=>void}){return <div className="kids">{list.map(s=><button key={s.id} onClick={()=>choose(s)}><i>{s.avatar}</i><b>{s.name}</b></button>)}</div>}
function Pick({title,list,value,set}:{title:string;list:string[];value:string;set:(v:string)=>void}){return <section><h3>{title}</h3><div className="emojis">{list.map(x=><button className={value===x?"on":""} key={x} onClick={()=>set(x)}>{x}</button>)}</div></section>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function TeacherMoodDetail({student,card,close}:{student:ManagedStudent;card?:PrintableData;close:()=>void}){return <div><button className="back-inline no-print" onClick={close}>← 목록으로</button>{card?<PrintableCard data={card} large/>:<Empty text={`${student.name}의 오늘 마음은 아직 작성되지 않았어요.`}/>}</div>}
function Individual({student,mood,friends,sent,received,total,note,saveNote}:{student:ManagedStudent;mood?:PrintableData;friends:PrintableData[];sent:PrintableData[];received:PrintableData[];total:number;note:string;saveNote:(v:string)=>void}){return <div className="individual"><h2>{student.avatar} {student.name}</h2><h3>오늘의 마음카드</h3>{mood?<PrintableCard data={mood}/>:<Empty text="오늘 마음을 아직 작성하지 않았어요."/>}<h3>최근 오늘의 마음친구 카드</h3>{friends.length?<div className="card-gallery">{friends.map(c=><PrintableCard key={c.id} data={c}/>)}</div>:<Empty text="최근 마음친구 카드가 없어요."/>}<h3>친구에게 보낸 자연 마음카드</h3>{sent.length?<div className="card-gallery">{sent.map(c=><PrintableCard key={c.id} data={c}/>)}</div>:<Empty text="보낸 자연 마음카드가 없어요."/>}<h3>친구에게 받은 자연 마음카드</h3>{received.length?<div className="card-gallery">{received.map(c=><PrintableCard key={c.id} data={c}/>)}</div>:<Empty text="받은 자연 마음카드가 없어요."/>}<section className="cycle-summary"><b>현재 자발적 마음 사이클</b><span>{sent.length} / {total}명에게 보냄</span></section><label className="teacher-note no-print">교사용 비공개 메모<textarea value={note} onChange={e=>saveNote(e.target.value)} placeholder="유아모드에는 절대 표시되지 않습니다."/></label></div>}
