"use client";
import {useRef,useState} from "react";import type {Sticker} from "@/lib/demo-v3";
export type NatureEdit={drawing?:string;stickers:Sticker[];audio?:string};
const stickerSet=["😊","🥰","😮","🌱","🌸","🌼","🍀","☀️","🌈","☁️","🌧️","⭐","🦋","❤️","💛","💚","💧"];
export default function NatureEditor({image,onChange}:{image:string;onChange:(v:NatureEdit)=>void}){const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),history=useRef<string[]>([]),recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);const [mode,setMode]=useState<"draw"|"sticker"|"sound">("draw"),[tool,setTool]=useState<"pen"|"eraser">("pen"),[color,setColor]=useState("#47725c"),[stickers,setStickers]=useState<Sticker[]>([]),[audio,setAudio]=useState(""),[recording,setRecording]=useState(false),[drag,setDrag]=useState("");
 const emit=(next?:Partial<NatureEdit>)=>onChange({drawing:canvas.current?.toDataURL(),stickers,audio,...next});const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*700/r.width,y:(e.clientY-r.top)*420/r.height}};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{history.current.push(canvas.current?.toDataURL()||"");drawing.current=true;const p=point(e),x=canvas.current!.getContext("2d")!;x.beginPath();x.moveTo(p.x,p.y)};const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const p=point(e),x=canvas.current!.getContext("2d")!;x.lineWidth=tool==="pen"?7:28;x.lineCap="round";x.strokeStyle=tool==="pen"?color:"#ffffff";x.globalCompositeOperation=tool==="pen"?"source-over":"destination-out";x.lineTo(p.x,p.y);x.stroke()};const end=()=>{drawing.current=false;emit()};
 const restore=(url?:string)=>{const c=canvas.current!,x=c.getContext("2d")!;x.clearRect(0,0,700,420);if(url){const i=new Image();i.onload=()=>{x.globalCompositeOperation="source-over";x.drawImage(i,0,0);emit()};i.src=url}else emit({drawing:undefined})};
 const add=(value:string)=>{const next=[...stickers,{id:`sticker-${Date.now()}`,value,x:45,y:45,size:52}];setStickers(next);onChange({drawing:canvas.current?.toDataURL(),stickers:next,audio})};const moveSticker=(id:string,x:number,y:number)=>{const next=stickers.map(s=>s.id===id?{...s,x,y}:s);setStickers(next);onChange({drawing:canvas.current?.toDataURL(),stickers:next,audio})};
 const record=async()=>{if(recording){recorder.current?.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=()=>{const reader=new FileReader();reader.onload=()=>{const v=String(reader.result);setAudio(v);emit({audio:v})};reader.readAsDataURL(new Blob(chunks.current,{type:r.mimeType}));stream.getTracks().forEach(t=>t.stop());setRecording(false)};r.start();recorder.current=r;setRecording(true);setTimeout(()=>r.state==="recording"&&r.stop(),20000)}catch{alert("마이크 권한을 허용해 주세요.")}};
 return <div className="nature-editor"><div className="nature-tabs"><button className={mode==="draw"?"active":""} onClick={()=>setMode("draw")}>✏️ 그려요</button><button className={mode==="sticker"?"active":""} onClick={()=>setMode("sticker")}>😊 꾸며요</button><button className={mode==="sound"?"active":""} onClick={()=>setMode("sound")}>🎙 소리를 담아요</button></div><div className="nature-stage" style={{backgroundImage:`url(${image})`}}><canvas ref={canvas} width={700} height={420} onPointerDown={mode==="draw"?start:undefined} onPointerMove={mode==="draw"?move:undefined} onPointerUp={end}/>{stickers.map(s=><button key={s.id} className="placed-sticker" style={{left:`${s.x}%`,top:`${s.y}%`,fontSize:s.size}} onPointerDown={e=>{setDrag(s.id);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag===s.id){const r=e.currentTarget.parentElement!.getBoundingClientRect();moveSticker(s.id,Math.max(3,Math.min(92,(e.clientX-r.left)/r.width*100)),Math.max(3,Math.min(88,(e.clientY-r.top)/r.height*100)))}}} onPointerUp={()=>setDrag("")} onDoubleClick={()=>{const next=stickers.filter(x=>x.id!==s.id);setStickers(next);onChange({drawing:canvas.current?.toDataURL(),stickers:next,audio})}}>{s.value}</button>)}</div>{mode==="draw"&&<div className="editor-tools"><button onClick={()=>setTool("pen")}>펜</button><button onClick={()=>setTool("eraser")}>지우개</button>{["#47725c","#e76f51","#f2b134","#4a90b8"].map(c=><button aria-label="색상" key={c} style={{background:c}} onClick={()=>{setColor(c);setTool("pen")}}/>)}<button onClick={()=>restore(history.current.pop())}>되돌리기</button><button onClick={()=>restore()}>모두 지우기</button></div>}{mode==="sticker"&&<><div className="sticker-palette">{stickerSet.map(s=><button key={s} onClick={()=>add(s)}>{s}</button>)}</div><p className="hint">스티커를 움직일 수 있어요. 두 번 누르면 지워져요.</p></>}{mode==="sound"&&<div className="sound-panel"><p>내 목소리도, 자연에서 들리는 소리도 담을 수 있어요.</p><button onClick={record}>{recording?"⏹ 담기 마치기":"🎙 소리를 담아요 (20초)"}</button>{audio&&<><audio controls src={audio}/><button onClick={record}>다시 담기</button></>}</div>}</div>}
