import {initialDemoState as initialV5,localDemoRepository as unusedV5,demoAuthService as baseAuth,releaseNextTreasures as baseRelease,sendNatureRecord as baseSend,studentAvatars,treasureReady,moodStats,privacyLabel,canView,demoAccounts,type DemoState as V5State,type FeatureSettings,type MoodEntry,type PersonalEntry,type ManagedStudent} from "./demo-v5.ts";
export {demoAuthService as baseAuth,releaseNextTreasures as baseRelease,sendNatureRecord as baseSend,studentAvatars,treasureReady,moodStats,privacyLabel,canView,demoAccounts};export type {FeatureSettings,MoodEntry,PersonalEntry,ManagedStudent};
export type StudentCredential={studentId:string;classId:string;qrToken:string;personalCode:string;studentCode:string;pin:string;version:number};
export type AccessSettings={qrEnabled:boolean;codeEnabled:boolean;sharedDevice:boolean;homeQrAllowed:boolean;teacherPin:string};
export type TeacherLetter={id:string;classId:string;studentId:string;teacherId?:string;createdAt:number;date:string;text?:string;emoji?:string;audio?:string;image?:string;drawing?:string;recordId?:string;recordKind?:"mood"|"discovery"|"capture";readAt?:number};
export type GalleryReaction={id:string;classId:string;galleryItemId:string;studentId:string;reactionType:"heart";createdAt:number};
export type GalleryReactionSettings={flowerEnabled:boolean;monthlySharerEnabled:boolean;exactCountsVisible:boolean;flowerThreshold:number;sharerThreshold:number};
export const defaultGalleryReactionSettings:GalleryReactionSettings={flowerEnabled:true,monthlySharerEnabled:true,exactCountsVisible:false,flowerThreshold:5,sharerThreshold:5};
export type TeacherDiscovery={id:string;classId:string;createdAt:number;date:string;title:string;image:string;drawing?:string;backgroundColor?:string;stickers:{id:string;value:string;x:number;y:number;size:number}[];audio?:string;text?:string;published:boolean};
export type AccessibilityPrefs={largeTargets:boolean;audioPrompts:boolean;simplifiedChoices:boolean;pictureGuidance:boolean;reducedMotion:boolean;extendedTimeout:boolean;tapAlternativeToDrag:boolean;teacherHelp:boolean};
export const defaultAccessibility:AccessibilityPrefs={largeTargets:false,audioPrompts:true,simplifiedChoices:false,pictureGuidance:true,reducedMotion:false,extendedTimeout:false,tapAlternativeToDrag:true,teacherHelp:true};
export type DemoState=V5State&{studentCredentials:StudentCredential[];accessSettings:Record<string,AccessSettings>;teacherLetters:TeacherLetter[];teacherDiscoveries:TeacherDiscovery[];galleryReactions:GalleryReaction[];galleryReactionCounts:Record<string,number>;galleryReactionSettings:Record<string,GalleryReactionSettings>;classAccessibility:Record<string,AccessibilityPrefs>;studentAccessibility:Record<string,Partial<AccessibilityPrefs>>};
export const demoAuthService={login:baseAuth.login,changePassword(classId:string,current:string,next:string,state:DemoState){return baseAuth.changePassword(classId,current,next,state) as DemoState},setInitialPassword(classId:string,next:string,state:DemoState){return baseAuth.setInitialPassword(classId,next,state) as DemoState},recover(id:string,key:string,next:string,state:DemoState){return baseAuth.recover(id,key,next,state) as DemoState},createClass(name:string,state:DemoState){const result=baseAuth.createClass(name,state),classId=result.account.classId,next={...result.state,studentCredentials:state.studentCredentials,accessSettings:{...state.accessSettings,[classId]:{qrEnabled:true,codeEnabled:false,sharedDevice:true,homeQrAllowed:true,teacherPin:"2468"}},galleryReactionSettings:{...state.galleryReactionSettings,[classId]:{...defaultGalleryReactionSettings}},classAccessibility:{...state.classAccessibility,[classId]:{...defaultAccessibility}}} as DemoState;return{state:next,account:result.account}}};
export function releaseNextTreasures(state:DemoState,classId:string){return baseRelease(state,classId) as DemoState}
export function sendNatureRecord(state:DemoState,input:Parameters<typeof baseSend>[1]){const result=baseSend(state,input);return{state:result.state as DemoState,roundCompleted:result.roundCompleted}}
const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function random(length:number){const values=new Uint32Array(length);crypto.getRandomValues(values);return [...values].map(v=>chars[v%chars.length]).join("")}
function digits(length:number){const values=new Uint32Array(length);crypto.getRandomValues(values);return [...values].map(v=>String(v%10)).join("")}
function secureQrToken(used:Set<string>){let token="";do{const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);token=`qrt_${[...bytes].map(value=>value.toString(16).padStart(2,"0")).join("")}`}while(used.has(token));used.add(token);return token}
function uniqueStudentCode(used:Set<string>){let code="";do{code=random(6)}while(used.has(code));used.add(code);return code}
function credential(studentId:string,classId:string,index:number,usedQr:Set<string>,usedCodes:Set<string>):StudentCredential{return{studentId,classId,qrToken:secureQrToken(usedQr),personalCode:`${random(3)}${String(index+1).padStart(2,"0")}`,studentCode:uniqueStudentCode(usedCodes),pin:digits(4),version:1}}
function normalizeAccessCredentials(credentials:StudentCredential[]){const usedQr=new Set<string>(),usedCodes=new Set<string>(),usedStudents=new Set<string>(),result:StudentCredential[]=[];for(const c of credentials){if(usedStudents.has(c.studentId))continue;usedStudents.add(c.studentId);const qrToken=c.qrToken&&!usedQr.has(c.qrToken)?(usedQr.add(c.qrToken),c.qrToken):secureQrToken(usedQr),studentCode=c.studentCode&&!usedCodes.has(c.studentCode)?(usedCodes.add(c.studentCode),c.studentCode):uniqueStudentCode(usedCodes);result.push(qrToken===c.qrToken&&studentCode===c.studentCode?c:{...c,qrToken,studentCode,version:(c.version||0)+1})}return result}
function upgrade(base:V5State):DemoState{const usedQr=new Set<string>(),usedCodes=new Set<string>(),credentials=base.classes.flatMap(c=>c.students.map((s,i)=>credential(s.id,c.id,i,usedQr,usedCodes)));return{...base,features:Object.fromEntries(base.classes.map(c=>[c.id,{...base.features[c.id],galleryReaction:base.features[c.id]?.galleryReaction??true,teacherLetter:base.features[c.id]?.teacherLetter??true}])),studentCredentials:credentials,accessSettings:Object.fromEntries(base.classes.map(c=>[c.id,{qrEnabled:true,codeEnabled:false,sharedDevice:true,homeQrAllowed:true,teacherPin:"2468"}])),teacherLetters:[],teacherDiscoveries:[],galleryReactions:[],galleryReactionCounts:{},galleryReactionSettings:Object.fromEntries(base.classes.map(c=>[c.id,{...defaultGalleryReactionSettings}])),classAccessibility:Object.fromEntries(base.classes.map(c=>[c.id,{...defaultAccessibility}])),studentAccessibility:{}}}
export const initialDemoState=():DemoState=>upgrade(initialV5());
const key="maeum-demo-v6";
export const localDemoRepository={load():DemoState{if(typeof window==="undefined")return initialDemoState();try{const raw=localStorage.getItem(key);if(raw){const state=JSON.parse(raw),credentials=normalizeAccessCredentials((state.studentCredentials||[]).map((c:StudentCredential)=>({...c,studentCode:c.studentCode||random(6),pin:c.pin||digits(4)})));return{...state,studentCredentials:credentials,teacherLetters:state.teacherLetters||[],teacherDiscoveries:state.teacherDiscoveries||[],galleryReactions:state.galleryReactions||[],galleryReactionCounts:state.galleryReactionCounts||{},galleryReactionSettings:Object.fromEntries(state.classes.map((c:{id:string})=>[c.id,{...defaultGalleryReactionSettings,...state.galleryReactionSettings?.[c.id]}])),features:Object.fromEntries(state.classes.map((c:{id:string})=>[c.id,{...state.features[c.id],galleryReaction:state.features[c.id]?.galleryReaction??true,teacherLetter:state.features[c.id]?.teacherLetter??true}])),classAccessibility:state.classAccessibility||Object.fromEntries(state.classes.map((c:{id:string})=>[c.id,{...defaultAccessibility}])),studentAccessibility:state.studentAccessibility||{}}};const previous=localStorage.getItem("maeum-demo-v5");return previous?upgrade(JSON.parse(previous)):initialDemoState()}catch{return initialDemoState()}},save(state:DemoState){if(typeof window==="undefined")return;try{const cloud=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL),strip=(value:any)=>typeof value==="string"&&value.startsWith("data:")?undefined:value;const compact=cloud?{...state,moodHistory:state.moodHistory.map(x=>({...x,image:strip(x.image),drawing:strip(x.drawing),audio:strip(x.audio)})),friendRecords:state.friendRecords.map(x=>({...x,drawing:strip(x.drawing),audio:strip(x.audio)})),natureCards:state.natureCards.map(x=>({...x,image:strip(x.image),drawing:strip(x.drawing),audio:strip(x.audio)})),personalEntries:state.personalEntries.map(x=>({...x,image:strip(x.image),drawing:strip(x.drawing),audio:strip(x.audio)})),teacherLetters:state.teacherLetters.map(x=>({...x,image:strip(x.image),drawing:strip(x.drawing),audio:strip(x.audio)}))}:state;localStorage.setItem(key,JSON.stringify(compact))}catch(error){console.warn("local cache save skipped",error instanceof Error?error.name:"unknown")}}};
export function ensureCredentials(state:DemoState){const locations=new Map(state.classes.flatMap(c=>c.students.map(student=>[student.id,c.id] as const))),enriched=normalizeAccessCredentials(state.studentCredentials.map(c=>({...c,classId:locations.get(c.studentId)||c.classId,studentCode:c.studentCode||random(6),pin:c.pin||digits(4)}))),known=new Set(enriched.map(c=>c.studentId)),usedQr=new Set(enriched.map(c=>c.qrToken)),usedCodes=new Set(enriched.map(c=>c.studentCode)),missing=state.classes.flatMap(c=>c.students.map((s,i)=>({c,s,i}))).filter(x=>!known.has(x.s.id));return missing.length?{...state,studentCredentials:[...enriched,...missing.map(x=>credential(x.s.id,x.c.id,x.i,usedQr,usedCodes))]}:{...state,studentCredentials:enriched}}
export type StudentIdentity={student:ManagedStudent;classId:string;credential:StudentCredential};
function resolveCredential(state:DemoState,credential:StudentCredential|undefined):StudentIdentity|null{if(!credential)return null;const matches=state.classes.flatMap(c=>c.students.filter(s=>s.id===credential.studentId).map(student=>({student,classId:c.id})));if(matches.length!==1||matches[0].classId!==credential.classId||!matches[0].student.active)return null;return{...matches[0],credential}}
export function resolveStudentByQr(state:DemoState,token:string){const matches=state.studentCredentials.filter(c=>c.qrToken===token);return matches.length===1?resolveCredential(state,matches[0]):null}
export function resolveStudentByCode(state:DemoState,code:string,pin:string){const matches=state.studentCredentials.filter(c=>c.studentCode===code.trim().toUpperCase()&&c.pin===pin.trim());return matches.length===1?resolveCredential(state,matches[0]):null}
export function teacherCanManageStudent(state:DemoState,teacherId:string,studentId:string){const account=state.accounts.find(a=>a.teacherId===teacherId),identity=state.classes.flatMap(c=>c.students.filter(s=>s.id===studentId).map(student=>({student,classId:c.id})));return !!account&&identity.length===1&&account.classId===identity[0].classId}
export function validateQr(state:DemoState,classId:string,token:string){const identity=resolveStudentByQr(state,token);return identity?.classId===classId?identity.student:null}
export function validatePersonalCode(state:DemoState,classId:string,code:string){const matches=state.studentCredentials.filter(c=>c.classId===classId&&c.personalCode===code.trim().toUpperCase());if(matches.length!==1)return null;const identity=resolveCredential(state,matches[0]);return identity?.classId===classId?identity.student:null}
export function validateStudentLogin(state:DemoState,code:string,pin:string){const identity=resolveStudentByCode(state,code,pin);return identity?{student:identity.student,classId:identity.classId}:null}
export function resetStudentPin(state:DemoState,studentId:string,pin?:string){return{...state,studentCredentials:state.studentCredentials.map(c=>c.studentId===studentId?{...c,pin:pin||digits(4)}:c)}}
export function regenerateQr(state:DemoState,studentId:string){const used=new Set(state.studentCredentials.filter(c=>c.studentId!==studentId).map(c=>c.qrToken)),qrToken=secureQrToken(used);return{...state,studentCredentials:state.studentCredentials.map(c=>c.studentId===studentId?{...c,qrToken,version:c.version+1}:c)}}
export const STUDENT_INACTIVITY_MS=5*60*1000,STUDENT_GRACE_MS=60*1000;
export type GalleryItem={id:string;classId:string;ownerId?:string;type:"nature"|"personal"|"teacher"};
export function publicGalleryItems(state:DemoState,classId:string):GalleryItem[]{return[...state.natureCards.filter(c=>c.classId===classId&&c.classShareRequested===true&&c.teacherApproved===true).map(c=>({id:c.id,classId,ownerId:c.from,type:"nature" as const})),...state.personalEntries.filter(e=>e.classId===classId&&e.privacyLevel==="class_share"&&e.teacherApproved===true).map(e=>({id:e.id,classId,ownerId:e.ownerId,type:"personal" as const})),...state.teacherDiscoveries.filter(e=>e.classId===classId&&e.published).map(e=>({id:e.id,classId,type:"teacher" as const}))]}
export function toggleGalleryReaction(state:DemoState,classId:string,studentId:string,galleryItemId:string){const active=state.classes.find(c=>c.id===classId)?.students.some(s=>s.id===studentId&&s.active),item=publicGalleryItems(state,classId).find(x=>x.id===galleryItemId);if(!active||!item||item.ownerId===studentId)return state;const exists=state.galleryReactions.some(r=>r.classId===classId&&r.galleryItemId===galleryItemId&&r.studentId===studentId&&r.reactionType==="heart");return{...state,galleryReactions:exists?state.galleryReactions.filter(r=>!(r.classId===classId&&r.galleryItemId===galleryItemId&&r.studentId===studentId&&r.reactionType==="heart")):[...state.galleryReactions,{id:`reaction-${crypto.randomUUID()}`,classId,galleryItemId,studentId,reactionType:"heart" as const,createdAt:Date.now()}]}}export function reactionCountForItem(state:DemoState,classId:string,galleryItemId:string){return new Set(state.galleryReactions.filter(r=>r.classId===classId&&r.galleryItemId===galleryItemId&&r.reactionType==="heart").map(r=>r.studentId)).size}
export function monthlyReactionSummary(state:DemoState,classId:string,month:string){const itemOwners=new Map([...state.natureCards.filter(x=>x.classId===classId).map(x=>[x.id,x.from] as const),...state.personalEntries.filter(x=>x.classId===classId).map(x=>[x.id,x.ownerId] as const)]),students=state.classes.find(c=>c.id===classId)?.students||[];return students.map(student=>{const sent=state.galleryReactions.filter(r=>r.classId===classId&&r.studentId===student.id&&new Date(r.createdAt).toISOString().slice(0,7)===month),distinctFriendIds=new Set(sent.map(r=>itemOwners.get(r.galleryItemId)).filter((owner):owner is string=>!!owner&&owner!==student.id)),ownedItems=publicGalleryItems(state,classId).filter(x=>x.ownerId===student.id),receivedWorks=ownedItems.filter(item=>reactionCountForItem(state,classId,item.id)>0).length,receivedReactions=ownedItems.reduce((total,item)=>total+reactionCountForItem(state,classId,item.id),0),flowerWorks=ownedItems.filter(item=>reactionCountForItem(state,classId,item.id)>=(state.galleryReactionSettings[classId]?.flowerThreshold??defaultGalleryReactionSettings.flowerThreshold)).length;return{studentId:student.id,distinctFriends:distinctFriendIds.size,reactionsSent:sent.length,receivedWorks,receivedReactions,flowerWorks}})}
