import {demoClasses} from "./demo-data.ts";
export type Attendance="present"|"absent"|"excluded";
export type ManagedStudent={id:string;name:string;avatar:string;active:boolean;attendance:Attendance};
export type ManagedClass={id:string;name:string;students:ManagedStudent[]};
export type TeacherAccount={classId:string;teacherId:string;password:string};
export type MoodRecord={a:string;b:string;note:string;drawing?:string;audio?:string;date:string};
export type FriendRecord={id:string;classId?:string;from:string;to:string;text?:string;drawing?:string;backgroundColor?:string;audio?:string;date:string};
export type Sticker={id:string,value:string,x:number,y:number,size:number};
export type NatureRecord={id:string;classId:string;from:string;to:string;image:string;drawing?:string;backgroundColor?:string;stickers:Sticker[];audio?:string;date:string;round:number;selectionOrder:number;releasedBatch?:number};
export type DemoState={classes:ManagedClass[];accounts:TeacherAccount[];moods:Record<string,MoodRecord>;friendRecords:FriendRecord[];natureCards:NatureRecord[];notes:Record<string,string>;rounds:Record<string,number>;releaseBatches:Record<string,number>};
export interface DemoRepository{load():DemoState;save(state:DemoState):void}
export const demoAccounts=[{classId:"sun",teacherId:"M7K4P2",password:"1234"},{classId:"star",teacherId:"B9R2X5",password:"1234"},{classId:"sprout",teacherId:"S4N8Q1",password:"1234"}];
export const initialDemoState=():DemoState=>({classes:demoClasses.map(c=>({...c,students:c.students.map(s=>({...s,active:true,attendance:"present" as const}))})),accounts:structuredClone(demoAccounts),moods:{},friendRecords:[],natureCards:[],notes:{},rounds:{},releaseBatches:{sun:0,star:0,sprout:0}});
const key="maeum-demo-v3";
export const localDemoRepository:DemoRepository={load(){if(typeof window==="undefined")return initialDemoState();try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):initialDemoState()}catch{return initialDemoState()}},save(state){if(typeof window!=="undefined")localStorage.setItem(key,JSON.stringify(state))}};
export interface DemoAuthService{login(id:string,password:string,state:DemoState):TeacherAccount|null;changePassword(classId:string,current:string,next:string,state:DemoState):DemoState}
export const demoAuthService:DemoAuthService={login(id,password,state){return state.accounts.find(a=>a.teacherId===id.trim().toUpperCase()&&a.password===password)||null},changePassword(classId,current,next,state){const account=state.accounts.find(a=>a.classId===classId);if(!account||account.password!==current)throw new Error("현재 비밀번호가 맞지 않아요.");return{...state,accounts:state.accounts.map(a=>a.classId===classId?{...a,password:next}:a)}}};
export const studentAvatars=["🐻","🐰","🦊","🐼","🐯","🐨","🐸","🐧","🦁","🐹","🐶","🐱","🦋","🐢","🐿️"];
export function sendNatureRecord(state:DemoState,input:Omit<NatureRecord,"round"|"selectionOrder"|"releasedBatch">){const cls=state.classes.find(c=>c.id===input.classId);if(!cls)throw new Error("학급을 찾을 수 없어요.");const active=cls.students.filter(s=>s.active),round=state.rounds[input.from]||1;if(input.from===input.to)throw new Error("자기 자신에게는 보낼 수 없어요.");const sent=state.natureCards.filter(c=>c.classId===input.classId&&c.from===input.from&&c.round===round);if(sent.some(c=>c.to===input.to))throw new Error("이번에는 이미 마음을 전한 친구예요.");const selectionOrder=sent.length+1,roundCompleted=selectionOrder>=Math.max(0,active.length-1),card:{releasedBatch?:number}&NatureRecord={...input,round,selectionOrder};return{state:{...state,natureCards:[...state.natureCards,card],rounds:roundCompleted?{...state.rounds,[input.from]:round+1}:state.rounds},roundCompleted}}
export function treasureReady(state:DemoState,classId:string){const cls=state.classes.find(c=>c.id===classId),active=cls?.students.filter(s=>s.active)||[];return active.length>0&&active.every(s=>state.natureCards.filter(c=>c.to===s.id&&!c.releasedBatch).length>=2)}
export function releaseNextTreasures(state:DemoState,classId:string){if(!treasureReady(state,classId))return state;const active=state.classes.find(c=>c.id===classId)!.students.filter(s=>s.active),batch=(state.releaseBatches[classId]||0)+1,chosen=new Set(active.flatMap(s=>state.natureCards.filter(c=>c.to===s.id&&!c.releasedBatch).slice(0,2).map(c=>c.id)));return{...state,natureCards:state.natureCards.map(c=>chosen.has(c.id)?{...c,releasedBatch:batch}:c),releaseBatches:{...state.releaseBatches,[classId]:batch}}}
