import {initialDemoState as initialV4,releaseNextTreasures as baseRelease,sendNatureRecord as baseSend,studentAvatars,treasureReady,moodStats,privacyLabel,canView,demoAccounts,type DemoState as V4State,type FeatureSettings,type MoodEntry,type PersonalEntry,type ManagedStudent} from "./demo-v4.ts";
export {studentAvatars,treasureReady,moodStats,privacyLabel,canView,demoAccounts};export type {FeatureSettings,MoodEntry,PersonalEntry,ManagedStudent};
export type TeacherAccount={classId:string;teacherId:string;password:string;classCode:string;recoveryKey:string;mustChangePassword:boolean};
export type DemoState=Omit<V4State,"accounts">&{accounts:TeacherAccount[]};
export function releaseNextTreasures(state:DemoState,classId:string){return baseRelease(state,classId) as DemoState}
export function sendNatureRecord(state:DemoState,input:Parameters<typeof baseSend>[1]){const result=baseSend(state,input);return{state:result.state as DemoState,roundCompleted:result.roundCompleted}}
const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function part(length:number){const values=new Uint32Array(length);crypto.getRandomValues(values);return [...values].map(v=>chars[v%chars.length]).join("")}
function unique(existing:Set<string>,make:()=>string){let value=make();while(existing.has(value))value=make();return value}
const upgrade=(base:V4State):DemoState=>({...base,accounts:base.accounts.map((a,i)=>({...a,classCode:["SUN1-M7K4","STAR-B9R2","SEED-S4N8"][i]||`${a.teacherId.slice(0,4)}-${part(4)}`,recoveryKey:["SUN1-M7K4-P2Q8","STAR-B9R2-X5Q7","SEED-S4N8-Q1P6"][i]||`${part(4)}-${part(4)}-${part(4)}`,mustChangePassword:false}))});
export const initialDemoState=():DemoState=>upgrade(initialV4());
const key="maeum-demo-v5";
export const localDemoRepository={load():DemoState{if(typeof window==="undefined")return initialDemoState();try{const raw=localStorage.getItem(key);if(raw)return JSON.parse(raw);const previous=localStorage.getItem("maeum-demo-v4");return previous?upgrade(JSON.parse(previous)):initialDemoState()}catch{return initialDemoState()}},save(state:DemoState){if(typeof window!=="undefined")localStorage.setItem(key,JSON.stringify(state))}};export const demoAuthService={
 login(id:string,password:string,state:DemoState){return state.accounts.find(a=>a.teacherId===id.trim().toUpperCase()&&a.password===password)||null},
 changePassword(classId:string,current:string,next:string,state:DemoState){const account=state.accounts.find(a=>a.classId===classId);if(!account||account.password!==current)throw new Error("현재 비밀번호가 맞지 않아요.");return{...state,accounts:state.accounts.map(a=>a.classId===classId?{...a,password:next,mustChangePassword:false}:a)}},
 setInitialPassword(classId:string,next:string,state:DemoState){return{...state,accounts:state.accounts.map(a=>a.classId===classId?{...a,password:next,mustChangePassword:false}:a)}},
 recover(teacherId:string,recoveryKey:string,next:string,state:DemoState){const account=state.accounts.find(a=>a.teacherId===teacherId.trim().toUpperCase()&&a.recoveryKey===recoveryKey.trim().toUpperCase());if(!account)throw new Error("교사 ID와 복구키를 다시 확인해 주세요.");return{...state,accounts:state.accounts.map(a=>a.classId===account.classId?{...a,password:next,mustChangePassword:false}:a)}},
 createClass(name:string,state:DemoState){const teacherId=unique(new Set(state.accounts.map(a=>a.teacherId)),()=>part(6)),classCode=unique(new Set(state.accounts.map(a=>a.classCode)),()=>`${part(4)}-${part(4)}`),recoveryKey=unique(new Set(state.accounts.map(a=>a.recoveryKey)),()=>`${part(4)}-${part(4)}-${part(4)}`),password=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,"0"),classId=`class-${crypto.randomUUID()}`,account={classId,teacherId,password,classCode,recoveryKey,mustChangePassword:true};return{state:{...state,classes:[...state.classes,{id:classId,name:name.trim(),students:[]}],accounts:[...state.accounts,account],features:{...state.features,[classId]:{mood:true,friend:true,nature:true,capture:true,discovery:true,treasure:true,galleryReaction:true}},discoveryTopics:{...state.discoveryTopics,[classId]:{title:"오늘의 발견",guide:"오늘 발견한 것을 너만의 방법으로 담아볼까요?",emoji:"🔎",startDate:"",endDate:""}}},account}}
};
