import assert from "node:assert/strict";
import {initialDemoState,regenerateQr,resetStudentPin,validatePersonalCode,validateQr,validateStudentLogin} from "../lib/demo-v6.ts";
let state=initialDemoState();const cls=state.classes[0],student=cls.students[0],credential=state.studentCredentials.find(c=>c.studentId===student.id);
assert.equal(credential.qrToken.includes(student.id),false);assert.equal(credential.qrToken.includes(cls.id),false);
assert.equal(validateQr(state,cls.id,credential.qrToken)?.id,student.id);assert.equal(validateQr(state,state.classes[1].id,credential.qrToken),null);
assert.equal(validatePersonalCode(state,cls.id,credential.personalCode)?.id,student.id);assert.equal(validateStudentLogin(state,credential.studentCode,credential.pin)?.student.id,student.id);assert.equal(validateStudentLogin(state,credential.studentCode,"000000"),null);assert.equal(new Set(state.studentCredentials.map(c=>c.studentCode)).size,state.studentCredentials.length);
const oldPin=credential.pin;state=resetStudentPin(state,student.id);const changedPin=state.studentCredentials.find(c=>c.studentId===student.id).pin;assert.notEqual(changedPin,oldPin);assert.equal(validateStudentLogin(state,credential.studentCode,oldPin),null);assert.equal(validateStudentLogin(state,credential.studentCode,changedPin)?.student.id,student.id);state={...state,classes:state.classes.map(c=>c.id===cls.id?{...c,students:c.students.map(s=>s.id===student.id?{...s,active:false}:s)}:c)};assert.equal(validateQr(state,cls.id,credential.qrToken),null);
state={...state,classes:state.classes.map(c=>c.id===cls.id?{...c,students:c.students.map(s=>s.id===student.id?{...s,active:true}:s)}:c)};const old=credential.qrToken;state=regenerateQr(state,student.id);const next=state.studentCredentials.find(c=>c.studentId===student.id);assert.notEqual(next.qrToken,old);assert.equal(validateQr(state,cls.id,old),null);assert.equal(validateQr(state,cls.id,next.qrToken)?.id,student.id);assert.equal(next.version,credential.version+1);
console.log("Shared-device credential checks passed");
