import assert from "node:assert/strict";
import {assignments} from "../lib/demo-data.ts";
import {canView,ensureCredentials,initialDemoState,regenerateQr,resetStudentPin,resolveStudentByCode,resolveStudentByQr,teacherCanManageStudent,validateQr} from "../lib/demo-v6.ts";
let state=ensureCredentials(initialDemoState());
const classA=state.classes[0],classB=state.classes[1],studentA=classA.students[0],studentB=classA.students[1],otherClassStudent=classB.students[0],credentialA=state.studentCredentials.find(c=>c.studentId===studentA.id);
const qrIdentity=resolveStudentByQr(state,credentialA.qrToken),codeIdentity=resolveStudentByCode(state,credentialA.studentCode,credentialA.pin);
assert.equal(qrIdentity.student.id,studentA.id);assert.equal(codeIdentity.student.id,studentA.id);assert.equal(qrIdentity.classId,classA.id);assert.equal(codeIdentity.classId,classA.id);
const wrongClassState={...state,studentCredentials:state.studentCredentials.map(c=>c.studentId===studentA.id?{...c,classId:classB.id}:c)};assert.equal(resolveStudentByQr(wrongClassState,credentialA.qrToken),null);assert.equal(resolveStudentByCode(wrongClassState,credentialA.studentCode,credentialA.pin),null);
const duplicateStudentState={...state,classes:state.classes.map(c=>c.id===classB.id?{...c,students:[...c.students,{...studentA}]}:c)};assert.equal(resolveStudentByQr(duplicateStudentState,credentialA.qrToken),null);assert.equal(resolveStudentByCode(duplicateStudentState,credentialA.studentCode,credentialA.pin),null);
const mood={id:"link-mood",classId:classA.id,ownerId:studentA.id,a:"😊",b:"🌱",note:"",date:"today",createdAt:1,privacyLevel:"teacher_private"};
const treasure={id:"link-treasure",classId:classA.id,ownerId:studentA.id,kind:"capture",title:"보물",image:"data:",stickers:[],date:"today",createdAt:2,privacyLevel:"class_share",teacherApproved:false};
const letter={id:"link-letter",classId:classA.id,studentId:studentA.id,teacherId:state.accounts[0].teacherId,createdAt:3,date:"today",text:"마음편지"};
state={...state,moodHistory:[...state.moodHistory,mood],personalEntries:[...state.personalEntries,treasure],teacherLetters:[...state.teacherLetters,letter]};
for(const identity of [resolveStudentByQr(state,credentialA.qrToken),resolveStudentByCode(state,credentialA.studentCode,credentialA.pin)]){assert.equal(state.moodHistory.filter(x=>x.ownerId===identity.student.id&&x.classId===identity.classId).at(-1).id,mood.id);assert.equal(state.personalEntries.filter(x=>x.ownerId===identity.student.id&&x.classId===identity.classId).at(-1).id,treasure.id);assert.equal(state.teacherLetters.filter(x=>x.studentId===identity.student.id&&x.classId===identity.classId).at(-1).id,letter.id)}
assert.equal(state.moodHistory.some(x=>x.ownerId===studentB.id&&x.id===mood.id),false);assert.equal(state.moodHistory.some(x=>x.classId===classB.id&&x.id===mood.id),false);
assert.equal(teacherCanManageStudent(state,state.accounts[0].teacherId,studentA.id),true);assert.equal(teacherCanManageStudent(state,state.accounts[0].teacherId,otherClassStudent.id),false);
assert.equal(canView(mood,{role:"student",studentId:studentA.id,classId:classA.id}),true);assert.equal(canView(mood,{role:"student",studentId:studentB.id,classId:classA.id}),false);assert.equal(canView({...mood,privacyLevel:"self_only"},{role:"teacher",classId:classA.id}),false);
const assigned=assignments(classA.students.filter(x=>x.active&&x.attendance==="present"));for(const [from,to] of assigned){assert.equal(classA.students.some(x=>x.id===from),true);assert.equal(classA.students.some(x=>x.id===to),true);assert.equal(classB.students.some(x=>x.id===to),false)}
assert.notDeepEqual(state.features[classA.id],state.features["missing"]);assert.notEqual(state.discoveryTopics[classA.id],state.discoveryTopics[classB.id]);
state={...state,classes:state.classes.map(c=>c.id===classA.id?{...c,students:c.students.map(x=>x.id===studentA.id?{...x,name:"새 이름",avatar:"🦊"}:x)}:c)};assert.equal(resolveStudentByQr(state,credentialA.qrToken).student.id,studentA.id);assert.equal(state.moodHistory.at(-1).ownerId,studentA.id);
const oldQr=credentialA.qrToken;state=regenerateQr(state,studentA.id);const newCredential=state.studentCredentials.find(c=>c.studentId===studentA.id);assert.equal(validateQr(state,classA.id,oldQr),null);assert.equal(resolveStudentByQr(state,newCredential.qrToken).student.id,studentA.id);assert.equal(state.moodHistory.at(-1).id,mood.id);
const oldPin=newCredential.pin;state=resetStudentPin(state,studentA.id);const resetCredential=state.studentCredentials.find(c=>c.studentId===studentA.id);assert.equal(resolveStudentByCode(state,resetCredential.studentCode,oldPin),null);assert.equal(resolveStudentByCode(state,resetCredential.studentCode,resetCredential.pin).student.id,studentA.id);assert.equal(state.personalEntries.at(-1).id,treasure.id);
state={...state,classes:state.classes.map(c=>c.id===classA.id?{...c,students:c.students.map(x=>x.id===studentA.id?{...x,active:false}:x)}:c)};assert.equal(resolveStudentByQr(state,resetCredential.qrToken),null);assert.equal(resolveStudentByCode(state,resetCredential.studentCode,resetCredential.pin),null);assert.equal(state.moodHistory.at(-1).id,mood.id);
console.log("Student-class-teacher linkage checks passed");
